--CRIANDO O BANCO
CREATE DATABASE EVENTOS2


-- CHAMANDO O BANCO
USE EVENTOS2

SELECT * 
FROM TB_EVENTOS2

-- CONTAR AS LINHAS PRA CHECAR
SELECT COUNT(DATA_EVNT)
FROM TB_EVENTOS2

-- CRIAÇÃO DE DIMENSÕES
	-- TIPO_EVENTOS
	-- COBERTURA
	-- COORDENADOR_RESP
	-- CONTRATANTE

-------------------- TIPO_EVENTOS--------------------
-- CRIANDO A DIMENSÃO TIPO_EVENTOS

SELECT *
FROM TB_EVENTOS2

-- ELIMINAR DUPLICADAS
SELECT DISTINCT(tipo_eventos)
FROM TB_EVENTOS2

-- INSERINDO NA DIMENSÃO
SELECT DISTINCT(tipo_eventos)
INTO din_tipo_eventos
FROM TB_EVENTOS2

-------------------- COBERTURA--------------------
-- CRIANDO A DIMENSÃO COBERTURA

SELECT *
FROM TB_EVENTOS2

-- ELIMINAR DUPLICADAS
SELECT DISTINCT(COBERTURA)
FROM TB_EVENTOS2

-- INSERINDO NA DIMENSÃO
SELECT DISTINCT(COBERTURA)
INTO din_cobertura
FROM TB_EVENTOS2

-------------------- COORDENADOR RESPONSÁVEL--------------------
-- CRIANDO A DIMENSÃO COORDENADOR RESPONSAVEL

SELECT *
FROM TB_EVENTOS2

-- ELIMINAR DUPLICADAS
SELECT DISTINCT(COORDENADOR_RESP)
FROM TB_EVENTOS2

-- INSERINDO NA DIMENSÃO
SELECT DISTINCT(COORDENADOR_RESP)
INTO din_coordenador_resp
FROM TB_EVENTOS2

-------------------- CONTRATANTE --------------------
-- CRIANDO A DIMENSÃO CONTRATANTE

SELECT *
FROM TB_EVENTOS2

-- ELIMINAR DUPLICADAS
SELECT DISTINCT(Contratante)
FROM TB_EVENTOS2

-- INSERINDO NA DIMENSÃO
SELECT DISTINCT(Contratante)
INTO din_Contratante
FROM TB_EVENTOS2

SELECT *
FROM din_Contratante


------------- CHECANDO AS TABELAS----------
SELECT * FROM din_tipo_eventos
SELECT * FROM din_cobertura
SELECT * FROM din_coordenador_resp
SELECT * FROM din_Contratante
SELECT * FROM TB_EVENTOS2

------------- DESCOBRINDO O RANGE DE DADTAS ----------
SELECT 
    MIN(data_evnt) AS Data_Inicial,
    MAX(data_evnt) AS Data_Final
FROM 
    TB_EVENTOS2;
