


SELECT *
FROM	TB_VENDAS

--======= TABELAS TEMPORARIAS ======= 


-- INSERINDO EM UMA TABELA TEMPORARIA (#)
SELECT *
INTO	#RELATORIO_LTZ
FROM	TB_VENDAS
WHERE	VENDEDOR = 'LTZ'



-- INSERINDO EM UMA TABELA TEMPORARIA CONSULTANDO EM OUTRA QUERY (##)
SELECT *
INTO	##RELATORIO
FROM	TB_VENDAS
WHERE	VENDEDOR = 'LTZ'


DROP TABLE ##RELATORIO
TRUNCATE TABLE ##RELATORIO

SELECT *
FROM	##RELATORIO

--====================================================


--========== CRIA플O DE TABELAS FISICAS--========== 



SELECT *
INTO	RELATORIO_LTZ
FROM	TB_VENDAS 
WHERE	VENDEDOR = 'LTZ'

DROP TABLE RELATORIO_LTZ


SELECT LOJA				AS	FILIAL
		,CUPOM			AS	TICKET
		,DATA
		,COD_CLIENTE	AS	CLIENTE
		,VENDEDOR
		,QUANTIDADE
		,VALOR_VENDA
		,VALOR_PAGO
		,VALOR_CANCELADO
INTO	RELATORIO_FINAL
FROM	RELATORIO_LTZ


SELECT *
FROM	RELATORIO_FINAL

--============= CRIA플O DE TABELA VIRTUAL COM TABELA FISICA --============= 



--CRIANDO A TABELA VIRTUAL
CREATE TABLE RELATORIO_NOVO
(
	FILIAL				INT
	,TICKET				INT
	,DATA				DATE
	,CLIENTE			VARCHAR(255)
	,COLABORADOR		VARCHAR(255)
	,QUANTIDADE			INT
	,VENDA				DECIMAL(18,2)
	,PAGO				DECIMAL(18,2)
	,CANCELADO	DECIMAL(18,2)
)

INSERT	INTO	RELATORIO_NOVO


SELECT 
	LOJA
	,CUPOM
	,DATA
	,COD_CLIENTE
	,VENDEDOR	
	,QUANTIDADE	
	,VALOR_VENDA		
	,VALOR_PAGO			
	,VALOR_CANCELADO	
FROM	TB_VENDAS


SELECT *
FROM	RELATORIO_NOVO
WHERE	VENDEDOR = 'VIN '

--============= CRIA플O DE VIEWS --============= 


CREATE VIEW VW_RELATORIO AS
SELECT	*
FROM	RELATORIO_NOVO


--============= TRATANDO OS ARQUIVOS --============= 

SELECT	
		TRIM(NOME)					AS NOME
		,RTRIM(COD_CLI)				AS CLIENTE
		,RTRIM(ENDERECO)			AS ENDERECO
		,RTRIM(CPF)					AS CPF
		,RTRIM(TIPO_DE_CLIENTE)		AS PERFIL
FROM TB_CLIENTES


CREATE VIEW RELATORIO_CLIENTE AS
SELECT	
		RTRIM(NOME)					AS NOME
		,RTRIM(COD_CLI)				AS CLIENTE
		,RTRIM(ENDERECO)			AS ENDERECO
		,RTRIM(CPF)					AS CPF
		,RTRIM(TIPO_DE_CLIENTE)		AS PERFIL
FROM TB_CLIENTES


SELECT *
FROM	RELATORIO_CLIENTE

Luiz Carlos de Oliveira


--=======================================
    --EXERCICIOS VIEWS + CRIA플O DE TABELA
--=======================================


--EXERCICIO 1
--PRIMEIRA PARA DO EXERCICIO CRIAR UMA TABELA FISICA TRATANDO SO CAMPOS COM OS TIPOS DE DADOS

--====================================================================

--EXERCICIO 2
--CRIAR UMA VIEW USANDO (SUM, FORMAT, BETWEEN, GROUP BY)
