USE TESTE;

SELECT *
FROM TB_VENDAS;


-- Case 1 
SELECT 
		LOJA
		, CUPOM
		, DATA
		, COD_CLIENTE
		, VENDEDOR


		,CASE VENDEDOR
		WHEN 'LTZ' THEN 'LUIZ TEIXEIRA ZUIM'
		WHEN 'LLP' THEN 'LUIS LOURENÇO PEREIRA'
		END AS [VENDEDOR]
FROM TB_VENDAS;

-- Case 2 
SELECT 
		LOJA
		, CUPOM
		, DATA
		, COD_CLIENTE
		, VENDEDOR
		, CASE 
		WHEN VENDEDOR IN ('LLP', 'LTZ', 'UGB') THEN 'VENDEDORES EXTERNOS'
		END AS [VENDEDOR]
FROM TB_VENDAS;


-- Case com or
SELECT 
		LOJA
		, CUPOM
		, DATA
		, COD_CLIENTE
		, VENDEDOR
		, CASE 
		WHEN VENDEDOR = 'LTZ' OR VENDEDOR = 'LLP' THEN 'VENDEDORES EXTERNOS'
		END AS [VENDEDOR]
FROM TB_VENDAS;