CREATE DATABASE TESTE;

USE TESTE;

SELECT *
FROM TB_VENDAS;

-- Tabelas temporárias


-- Inserindo em tabela temporária
SELECT *
INTO #RELATORIO_LTZ
FROM TB_VENDAS
WHERE VENDEDOR = 'LTZ';


-- Inserindo em tabela temporária seção ativa e outra seção
SELECT *
INTO ##RELATORIO
FROM TB_VENDAS
WHERE VENDEDOR = 'LTZ';

--DROP TABLE ##RELATORIO_LTZ


SELECT *
INTO RELATORIO_LTZ
FROM TB_VENDAS
WHERE VENDEDOR = 'LTZ'

--DROP TABLE RELATORIO_LTZ

SELECT LOJA                AS FILIAL
	   , CUPOM             AS TICKET
	   , DATA             
	   , COD_CLIENTE       AS CLIENTE
	   , VENDEDOR
	   , QUANTIDADE
	   , VALOR_VENDA
	   , VALOR_PAGO
	   , VALOR_CANCELADO
INTO   RELATORIO_FINAL
FROM   #RELATORIO_LTZ

SELECT *
FROM RELATORIO_FINAL;


-- Criando a tabela virtual
CREATE TABLE RELATORIO_NOVO
(
	 FILIAL           INT                   
	, TICKET          INT
	, DATA            DATE
	, CLIENTE         VARCHAR(255)
	, COLAORADOR      VARCHAR(255)
	, QUANTIDADE      INT
	, VENDA           DECIMAL(18,2)
	, PAGO            DECIMAL(18,2)
	, CANCELADO       DECIMAL(18,2)
)
INSERT INTO RELATORIO_NOVO

SELECT
	 LOJA                                      
	, CUPOM                 
	, DATA                  
	, COD_CLIENTE           
	, VENDEDOR              
	, QUANTIDADE            
	, VALOR_VENDA           
	, VALOR_PAGO            
	, VALOR_CANCELADO       
FROM TB_VENDAS

SELECT *
FROM RELATORIO_NOVO

--VIEWS
SELECT *
FROM RELATORIO_NOVO

CREATE VIEW VW_RELATORIO AS
SELECT *
FROM RELATORIO_NOVO

SELECT *
FROM VW_RELATORIO

SELECT 
		RTRIM(NOME)					AS NOME	
		, RTRIM(COD_CLI)			AS CLIENTE
		, RTRIM(ENDERECO)			AS ENDERECO
		, RTRIM(CPF)				AS CPF
		, RTRIM(TIPO_DE_CLIENTE)	AS PERFIL
FROM TB_CLIENTES	


CREATE VIEW RELATORIO_CLIENTE AS
SELECT 
		RTRIM(NOME)					AS NOME	
		, RTRIM(COD_CLI)			AS CLIENTE
		, RTRIM(ENDERECO)			AS ENDERECO
		, RTRIM(CPF)				AS CPF
		, RTRIM(TIPO_DE_CLIENTE)	AS PERFIL
FROM TB_CLIENTES

SELECT *

FROM RELATORIO_CLIENTE

SELECT *
FROM TB_CLIENTES