--USE TESTE;

--SELECT *
--FROM TB_VENDAS
--WHERE VENDEDOR = 'LUIZ LOPES'

---- BEGIN
---- ROLLBACK
---- COMMIT

--BEGIN TRAN                     -- 
--UPDATE TB_VENDAS             -- TABELA PARA SER ALTERADA
--SET    VENDEDOR = 'LUIZ LOPES' -- CAMPO A SER ALTERADO
--WHERE  VENDEDOR = 'LLP'

--COMMIT

-- UPDATE
SELECT *
FROM   TB_VENDAS
WHERE  VENDEDOR = 'LTZ'

BEGIN TRAN
UPDATE TB_VENDAS
SET    VENDEDOR = 'LUIZ TOORREZ'
WHERE  VENDEDOR = 'LTZ'

COMMIT

SELECT *
FROM TB_VENDAS
WHERE VENDEDOR = 'UGB'
AND   QUANTIDADE > 2

BEGIN TRAN
UPDATE TB_VENDAS
SET    VENDEDOR = 'UMBERTO'
WHERE VENDEDOR = 'UGB'
AND   QUANTIDADE > 2

COMMIT